version: '3'
services:
 keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    labels:
      - traefik.enable=true 
      - traefik.http.routers.keycloak.rule=Host(`keycloak.domain.com`) 
      - traefik.http.routers.keycloak.entrypoints=websecure  
      - traefik.http.routers.keycloak.tls.certresolver=letsencrypt
      - traefik.http.routers.keycloak.tls=true
      - traefik.http.services.keycloak.loadbalancer.server.port=8080
    command:
      - "start"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=
      - KC_HOSTNAME_URL=https://keycloak.domain.com
      - KC_DB=mariadb
      - KC_DB_URL=jdbc:mariadb://mariadb:3306/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=
      - KC_HTTPS_CERTIFICATE_FILE=config/fullchain.pem
      - KC_HTTPS_CERTIFICATE_KEY_FILE=config/keyfile.pem
      - KC_PROXY=edge
      - KC_HOSTNAME_DEBUG=true
      - KC_HOSTNAME_STRICT_BACKCHANNEL=true
    volumes:
      - {path to config}/keycloak/config:/config
    networks:
      - proxied_apps
      - ldap
      - oauth
      - mariadb
    ports:
      - 8443:8443
      - 8180:8080
    restart: always

networks:
  oauth:
    name: oauth
  ldap:
    external: true
  mariadb:
    external: true
  proxied_apps:
    external: true