version: "3"
services:
#Used to update the ip of your domain on cloudflare
 ddns:
    image: oznu/cloudflare-ddns:latest
    container_name: ddns
    networks:
      - ddns
    environment:
      - API_KEY=
      - ZONE=
      - PROXIED=false
    restart: always

networks:
  ddns:
    name: ddns