version: "3"
services:

  traefik:
    image: traefik:latest
    container_name: traefik
    command: --api.insecure=true --providers.docker
    environment:
      - CF_API_EMAIL=
      - CF_API_KEY=
    ports:
      - 80:80
      - 443:443
      - 8181:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - {path to config}/traefik/config:/etc/traefik
    networks:
      - proxied_apps
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.domain.com`)
      - traefik.http.routers.traefik.entryPoints=console
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=forward-auth@file

      - traefik.http.services.traefikssl.loadbalancer.server.port=8181
      - traefik.http.routers.traefikssl.rule=Host(`traefik.domain.com`)
      - traefik.http.routers.traefikssl.middlewares=forward-auth@file
      - traefik.http.routers.traefikssl.entrypoints=websecure
      - traefik.http.routers.traefikssl.service=api@internal
      - traefik.http.routers.traefikssl.tls.certresolver=letsencrypt

      - traefik.http.routers.api.tls.domains[0].main=domain.com
      - traefik.http.routers.api.tls.domains[0].sans=*.domain.com
      - traefik.http.routers.api.tls.domains[1].main=otherdomain.win
      - traefik.http.routers.api.tls.domains[1].sans=*.otherdomain.win
      - traefik.http.routers.api.tls.certResolver=letsencrypt
    restart: unless-stopped

#####################################################################

  forward-auth:
    container_name: forward-auth
    image: thomseddon/traefik-forward-auth:2
    networks:
      - proxied_apps
      - oauth
    environment:
      - AUTH_HOST=auth.domain.com
      - COOKIE_DOMAIN=domain.com
      - SECRET=
      - URL_PATH=/_oauth
      - PORT=4181
      - DEFAULT_PROVIDER=oidc
      - PROVIDERS_OIDC_ISSUER_URL=https://keycloak.domain.com/realms/{realmid}
      - PROVIDERS_OIDC_CLIENT_ID=traefik
      - PROVIDERS_OIDC_CLIENT_SECRET=
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181
      - traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User

      - traefik.http.routers.traefik-forward-auth.rule=Host(`auth.roboter5123.com`) 
      - traefik.http.routers.traefik-forward-auth.entrypoints=websecure  
      - traefik.http.routers.traefik-forward-auth.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik-forward-auth.tls=true
      - traefik.http.routers.traefik-forward-auth.middlewares=forward-auth@file
      - traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181


networks:
  proxied_apps:
    name: proxied_apps
  oauth:
    external: true