version: '3'
services:

# Used to update containers automaticly
 watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    command: --interval 30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - watchtower
    restart: unless-stopped  

networks:
  watchtower:
   name: watchtower